[config]
schemaVersion = "0.0.1"

[package]
namespace = "ykysnk"
name = "BepinExUtils"
versionNumber = "0.0.1" # will be replaced
description = "Utils for BepinEx"
websiteUrl = "https://github.com/T2PeNBiX99wcoxKv3A4g/BepinEx-Utils"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack_Silksong = "5.4.2304"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["hollow-knight-silksong", ]
[publish.categories]
hollow-knight-silksong = ["mods", "libraries", ]
